AUTO_SRC_PATH_MASK=$AUTOCTI_EDEN_PATH"/autocti/mask"
VIS_SRC_PATH_MASK=$PYEUCLID_CTI_PATH"/VIS_CTI_AutoCTI_Mask/python/VIS_CTI_AutoCTI_Mask"

cp -r $AUTO_SRC_PATH_MASK/* $VIS_SRC_PATH_MASK/
cp $AUTO_SRC_PATH_MASK/__init__.py $VIS_SRC_PATH_MASK/

AUTO_TEST_PATH_MASK=$AUTOCTI_EDEN_PATH/"test_autocti/unit/mask"
VIS_TEST_PATH_MASK=$PYEUCLID_CTI_PATH"/VIS_CTI_AutoCTI_Mask/tests/python"

cp -r $AUTO_TEST_PATH_MASK/* $VIS_TEST_PATH_MASK/

rm -rf $VIS_TEST_PATH_MASK/__init__.py